### ISSUE TITLE
Install 32 bits packages on 64 bits systems

### ISSUE THREAD

**Issue by RobertoSchneiders** [chef-windows/vcruntime#5]
Sometime you need to install 32 bits packages on 64 bits systems and this cookbook doesn't allow that. (Eg: Installing PGAdmin III)

I was thinking in add a new attribute for that (32/64). If informed we use that, otherwise we use the attribute.

Other option is to create specific recipes, like, `vcruntime::vc12::32`, `vcruntime::vc12::64`.

What do you think?

**Comment by axelrtgs** [comment]
if https://github.com/chef-windows/vcruntime/pull/8 gets accepted and merged this will be included and can be closed

**Comment by tas50** [comment]
#8 fixes this and has been merged
